name: Release JAR al crear tag

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Empaquetar (sin tests)
        run: mvn -B -ntp -DskipTests package
      - name: Crear Release y subir JAR
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
